function [fitresult, gof] = createFit(x, y, z)
%CREATEFIT1(X,Y,Z)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Input : y
%      Z Output: z
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 30-Jan-2018 12:06:59


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( x, y, z );

% Set up fittype and options.
ft = fittype( 'a*(x^b)+(c*y)+d*(x*y)', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.060018819779476 0.866749896999319 0.631188734269011 0.355073651878849];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% % Create a figure for the plots.
% figure( 'Name', 'untitled fit 1' );
% 
% % Plot fit with data.
% subplot( 2, 1, 1 );
% h = plot( fitresult, [xData, yData], zData );
% legend( h, 'untitled fit 1', 'z vs. x, y', 'Location', 'NorthEast' );
% % Label axes
% xlabel x
% ylabel y
% zlabel z
% grid on
% view( -3.1, 20.1 );
% 
% % Make contour plot.
% subplot( 2, 1, 2 );
% h = plot( fitresult, [xData, yData], zData, 'Style', 'Contour' );
% legend( h, 'untitled fit 1', 'z vs. x, y', 'Location', 'NorthEast' );
% % Label axes
% xlabel x
% ylabel y
% grid on


